package com.github.ysbbbbbb.kaleidoscopedoll.event;

import com.github.ysbbbbbb.kaleidoscopedoll.KaleidoscopeDoll;
import com.github.ysbbbbbb.kaleidoscopedoll.block.DollBlock;
import com.github.ysbbbbbb.kaleidoscopedoll.item.DollItem;
import com.google.common.collect.Maps;
import com.google.common.collect.Sets;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegisterEvent;

import java.util.Map;
import java.util.Set;
import java.util.stream.IntStream;

@Mod.EventBusSubscriber(modid = KaleidoscopeDoll.MOD_ID, bus = Mod.EventBusSubscriber.Bus.MOD)
public class ModRegisterEvent {
    public static final Map<ResourceLocation, DollBlock> DOLL_BLOCKS = Maps.newLinkedHashMap();
    public static final Map<ResourceLocation, String> VANILLA_TOOLTIPS = Maps.newHashMap();
    public static final Map<ResourceLocation, String> SPECIAL_TOOLTIPS = Maps.newHashMap();
    public static final Set<Item> DOLL_ITEMS = Sets.newLinkedHashSet();
    private static final int MAX_DOLL_COUNT = 458;

    private static void registerAllVanillaTooltips() {
        registerVanillaTooltips("doll_328", "wine_fox");
        registerVanillaTooltips("doll_329", "dokimobs_warden");
    }

    private static void registerAllSpecialTooltips() {
        registerSpecialTooltips("doll_0", "author_ysbb");
        registerSpecialTooltips("doll_1", "author_tartaric_acid");
        registerSpecialTooltips("doll_67", "author_abert_cat");
        registerSpecialTooltips("doll_68", "author_cr_019");

        registerSpecialTooltips("doll_69", "sponsors_guriformes");
        registerSpecialTooltips("doll_70", "sponsors_passer1ne");
        registerSpecialTooltips("doll_71", "sponsors_tanyeng");
        registerSpecialTooltips("doll_72", "sponsors_airsamafurry");
        registerSpecialTooltips("doll_73", "sponsors_corleonejing");
        registerSpecialTooltips("doll_74", "sponsors_kuriyamayasura");
        registerSpecialTooltips("doll_75", "sponsors_miomilost");
        registerSpecialTooltips("doll_76", "sponsors_nekonymph");
        registerSpecialTooltips("doll_77", "sponsors_puerkimiko");
        registerSpecialTooltips("doll_78", "sponsors_aoisake");
        registerSpecialTooltips("doll_79", "sponsors_cpcian39");
        registerSpecialTooltips("doll_80", "sponsors_swordman_live");
        registerSpecialTooltips("doll_81", "sponsors_tclimuareotin");
        registerSpecialTooltips("doll_82", "sponsors_taste_puppy");
        registerSpecialTooltips("doll_83", "sponsors_poetry_chicken");
        registerSpecialTooltips("doll_84", "sponsors_fudge_666");
        registerSpecialTooltips("doll_85", "sponsors_chair341");
        registerSpecialTooltips("doll_86", "sponsors_dumnheint");
        registerSpecialTooltips("doll_87", "sponsors_lilunli");
        registerSpecialTooltips("doll_88", "sponsors_psbastards");
        registerSpecialTooltips("doll_89", "sponsors_pysgas");
        registerSpecialTooltips("doll_90", "sponsors_redflashier");
        registerSpecialTooltips("doll_91", "sponsors_rsob123");
        registerSpecialTooltips("doll_92", "sponsors_solareclipseg");
        registerSpecialTooltips("doll_93", "sponsors_zombiec1107");
        registerSpecialTooltips("doll_94", "sponsors__moepus_");
        registerSpecialTooltips("doll_95", "sponsors_ackrf");
        registerSpecialTooltips("doll_96", "sponsors_chuanchengzi");
        registerSpecialTooltips("doll_97", "sponsors_deltaex001");
        registerSpecialTooltips("doll_98", "sponsors_elyasrosedale");
        registerSpecialTooltips("doll_99", "sponsors_faustduck");
        registerSpecialTooltips("doll_100", "sponsors_lixu223");
        registerSpecialTooltips("doll_101", "sponsors_kupurrra");
        registerSpecialTooltips("doll_102", "sponsors_thjnd");
        registerSpecialTooltips("doll_103", "sponsors_variant_dk");
        registerSpecialTooltips("doll_104", "sponsors_yuxiaowan");
        registerSpecialTooltips("doll_105", "sponsors_bigpear5231");
        registerSpecialTooltips("doll_106", "sponsors_idlersnacl");
        registerSpecialTooltips("doll_107", "sponsors_kekmc123");
        registerSpecialTooltips("doll_108", "sponsors_kizunahovene");
        registerSpecialTooltips("doll_109", "sponsors_linx");
        registerSpecialTooltips("doll_110", "sponsors_linx_su");
        registerSpecialTooltips("doll_111", "sponsors_wyx0714");
        registerSpecialTooltips("doll_112", "sponsors_xheya_3u3");
        registerSpecialTooltips("doll_113", "sponsors_1ye_kul");
        registerSpecialTooltips("doll_114", "sponsors_aleph_2");
        registerSpecialTooltips("doll_115", "sponsors_apomona");
        registerSpecialTooltips("doll_116", "sponsors_atkingqvq");
        registerSpecialTooltips("doll_117", "sponsors_bestshaaku");
        registerSpecialTooltips("doll_118", "sponsors_blackannin");
        registerSpecialTooltips("doll_119", "sponsors_ca1_t0u");
        registerSpecialTooltips("doll_120", "sponsors_catbug");
        registerSpecialTooltips("doll_121", "sponsors_catjoy6493");
        registerSpecialTooltips("doll_122", "sponsors_catlikesleep1160");
        registerSpecialTooltips("doll_123", "sponsors_cdrsimon");
        registerSpecialTooltips("doll_124", "sponsors_celia4300");
        registerSpecialTooltips("doll_125", "sponsors_monicanya");
        registerSpecialTooltips("doll_126", "sponsors_creamtea2542");
        registerSpecialTooltips("doll_127", "sponsors_cxzkkaa");
        registerSpecialTooltips("doll_128", "sponsors_dafeimao");
        registerSpecialTooltips("doll_129", "sponsors_dazhuo1");
        registerSpecialTooltips("doll_130", "sponsors_dongfang_qian");
        registerSpecialTooltips("doll_131", "sponsors_eat_grass_");
        registerSpecialTooltips("doll_132", "sponsors_echoing_phantom");
        registerSpecialTooltips("doll_133", "sponsors_elex7310");
        registerSpecialTooltips("doll_134", "sponsors_entropy_yeah");
        registerSpecialTooltips("doll_135", "sponsors_eteroo44");
        registerSpecialTooltips("doll_136", "sponsors_fishinblack");
        registerSpecialTooltips("doll_137", "sponsors_foxxie");
        registerSpecialTooltips("doll_138", "sponsors_gfboy");
        registerSpecialTooltips("doll_139", "sponsors_gouzi_jun");
        registerSpecialTooltips("doll_140", "sponsors_gzq777");
        registerSpecialTooltips("doll_141", "sponsors_g_papy");
        registerSpecialTooltips("doll_142", "sponsors_hardypuro");
        registerSpecialTooltips("doll_143", "sponsors_hinijikata");
        registerSpecialTooltips("doll_144", "sponsors_ike_sonata");
        registerSpecialTooltips("doll_145", "sponsors_inky_mad");
        registerSpecialTooltips("doll_146", "sponsors_jg_aurora");
        registerSpecialTooltips("doll_147", "sponsors_jia1chen");
        registerSpecialTooltips("doll_148", "sponsors_jiaqihuang");
        registerSpecialTooltips("doll_149", "sponsors_jijiwawa");
        registerSpecialTooltips("doll_150", "sponsors_jm_wuyan");
        registerSpecialTooltips("doll_151", "sponsors_kaixiaoli_li");
        registerSpecialTooltips("doll_152", "sponsors_kaltsiit");
        registerSpecialTooltips("doll_153", "sponsors_kal_crane");
        registerSpecialTooltips("doll_154", "sponsors_kelvin");
        registerSpecialTooltips("doll_155", "sponsors_kuiper_hooligans");
        registerSpecialTooltips("doll_156", "sponsors_lantehall");
        registerSpecialTooltips("doll_157", "sponsors_legitchunk");
        registerSpecialTooltips("doll_158", "sponsors_limfx");
        registerSpecialTooltips("doll_159", "sponsors_lingjinzi");
        registerSpecialTooltips("doll_160", "sponsors_lingrengui");
        registerSpecialTooltips("doll_161", "sponsors_ling_e_iswolf");
        registerSpecialTooltips("doll_162", "sponsors_liulian");
        registerSpecialTooltips("doll_163", "sponsors_long_shu");
        registerSpecialTooltips("doll_164", "sponsors_luohammer");
        registerSpecialTooltips("doll_165", "sponsors_marguarita");
        registerSpecialTooltips("doll_166", "sponsors_mingqijiang");
        registerSpecialTooltips("doll_167", "sponsors_miya");
        registerSpecialTooltips("doll_168", "sponsors_mochcanl");
        registerSpecialTooltips("doll_169", "sponsors_mtraptrix");
        registerSpecialTooltips("doll_170", "sponsors_mu_ni_dian");
        registerSpecialTooltips("doll_171", "sponsors_nigella");
        registerSpecialTooltips("doll_172", "sponsors_nina_yxj");
        registerSpecialTooltips("doll_173", "sponsors_nuperaki");
        registerSpecialTooltips("doll_174", "sponsors_panta_lone");
        registerSpecialTooltips("doll_175", "sponsors_q821");
        registerSpecialTooltips("doll_176", "sponsors_qi_qingm");
        registerSpecialTooltips("doll_177", "sponsors_qxiaochai");
        registerSpecialTooltips("doll_178", "sponsors_revisorytoast22");
        registerSpecialTooltips("doll_179", "sponsors_saelens16");
        registerSpecialTooltips("doll_180", "sponsors_shiinanomashiro");
        registerSpecialTooltips("doll_181", "sponsors_shovei_");
        registerSpecialTooltips("doll_182", "sponsors_thirteny13");
        registerSpecialTooltips("doll_183", "sponsors_thunder50bmg");
        registerSpecialTooltips("doll_184", "sponsors_trance0203");
        registerSpecialTooltips("doll_185", "sponsors_usoko");
        registerSpecialTooltips("doll_186", "sponsors_xian__yue");
        registerSpecialTooltips("doll_187", "sponsors_xin_yucll");
        registerSpecialTooltips("doll_188", "sponsors_xlrm");
        registerSpecialTooltips("doll_189", "sponsors_xuanyou_awa");
        registerSpecialTooltips("doll_190", "sponsors_xvangezi");
        registerSpecialTooltips("doll_191", "sponsors_yili_olen");
        registerSpecialTooltips("doll_192", "sponsors_yuan_fe");
        registerSpecialTooltips("doll_193", "sponsors_yuroli73");
        registerSpecialTooltips("doll_194", "sponsors__aorta_");
        registerSpecialTooltips("doll_195", "sponsors__haman_");
        registerSpecialTooltips("doll_196", "sponsors_kelvin_0");
        registerSpecialTooltips("doll_197", "sponsors_sfshuofang");
        registerSpecialTooltips("doll_198", "sponsors_xvp1563");
        registerSpecialTooltips("doll_199", "sponsors_swamp_puppy");
        registerSpecialTooltips("doll_200", "sponsors_aigoth_");
        registerSpecialTooltips("doll_201", "sponsors_airphen");
        registerSpecialTooltips("doll_202", "sponsors_a_youyou");
        registerSpecialTooltips("doll_203", "sponsors_baiseduya");
        registerSpecialTooltips("doll_204", "sponsors_beankk");
        registerSpecialTooltips("doll_205", "sponsors_benpao216");
        registerSpecialTooltips("doll_206", "sponsors_caelumsora");
        registerSpecialTooltips("doll_207", "sponsors_careep1225");
        registerSpecialTooltips("doll_208", "sponsors_chan_yang");
        registerSpecialTooltips("doll_209", "sponsors_chat4455");
        registerSpecialTooltips("doll_210", "sponsors_claoc");
        registerSpecialTooltips("doll_211", "sponsors_cn2049");
        registerSpecialTooltips("doll_212", "sponsors_cubekc");
        registerSpecialTooltips("doll_213", "sponsors_daichenguanggai");
        registerSpecialTooltips("doll_214", "sponsors_dfg233");
        registerSpecialTooltips("doll_215", "sponsors_dx_zimu");
        registerSpecialTooltips("doll_216", "sponsors_fantasy_sunny");
        registerSpecialTooltips("doll_217", "sponsors_gui__he");
        registerSpecialTooltips("doll_218", "sponsors_hayase_gusuri");
        registerSpecialTooltips("doll_219", "sponsors_hctl62");
        registerSpecialTooltips("doll_220", "sponsors_jiaojiaofish");
        registerSpecialTooltips("doll_221", "sponsors_jinwu_mofern");
        registerSpecialTooltips("doll_222", "sponsors_meow_lynxsea");
        registerSpecialTooltips("doll_223", "sponsors_misaka18866");
        registerSpecialTooltips("doll_224", "sponsors_mmhhqwq");
        registerSpecialTooltips("doll_225", "sponsors_mzuinit");
        registerSpecialTooltips("doll_226", "sponsors_naci_gt");
        registerSpecialTooltips("doll_227", "sponsors_niannianan");
        registerSpecialTooltips("doll_228", "sponsors_only_my_sky");
        registerSpecialTooltips("doll_229", "sponsors_pumpkin_jn");
        registerSpecialTooltips("doll_230", "sponsors_purplecomet1793");
        registerSpecialTooltips("doll_231", "sponsors_qianmoumouuu");
        registerSpecialTooltips("doll_232", "sponsors_qingxun49");
        registerSpecialTooltips("doll_233", "sponsors_qmcaaaaa");
        registerSpecialTooltips("doll_234", "sponsors_qyhumansociety");
        registerSpecialTooltips("doll_235", "sponsors_reiujiutsuho123");
        registerSpecialTooltips("doll_236", "sponsors_ru0000");
        registerSpecialTooltips("doll_237", "sponsors_sekiyama2n");
        registerSpecialTooltips("doll_238", "sponsors_shanhai_1778");
        registerSpecialTooltips("doll_239", "sponsors_sheepythecaty");
        registerSpecialTooltips("doll_240", "sponsors_shirin1214");
        registerSpecialTooltips("doll_241", "sponsors_sikoishi514");
        registerSpecialTooltips("doll_242", "sponsors_simulsiho");
        registerSpecialTooltips("doll_243", "sponsors_sufferay");
        registerSpecialTooltips("doll_244", "sponsors_surpgenmiko");
        registerSpecialTooltips("doll_245", "sponsors_taitaitaiya");
        registerSpecialTooltips("doll_246", "sponsors_taosisi");
        registerSpecialTooltips("doll_247", "sponsors_tengram");
        registerSpecialTooltips("doll_248", "sponsors_tianmo369");
        registerSpecialTooltips("doll_249", "sponsors_vanessa");
        registerSpecialTooltips("doll_250", "sponsors_vihk");
        registerSpecialTooltips("doll_251", "sponsors_white_kirby");
        registerSpecialTooltips("doll_252", "sponsors_woaijiaying123");
        registerSpecialTooltips("doll_253", "sponsors_wuyu_owo");
        registerSpecialTooltips("doll_254", "sponsors_xiaaopenng");
        registerSpecialTooltips("doll_255", "sponsors_ximo_xiaomo");
        registerSpecialTooltips("doll_256", "sponsors_xxx");
        registerSpecialTooltips("doll_257", "sponsors_ye_qiufeng");
        registerSpecialTooltips("doll_258", "sponsors_yongfa");
        registerSpecialTooltips("doll_259", "sponsors_yue_guan_xing");
        registerSpecialTooltips("doll_260", "sponsors_zaskgost");
        registerSpecialTooltips("doll_261", "sponsors__baka_9");
        registerSpecialTooltips("doll_262", "sponsors_lezhengyinying");
        registerSpecialTooltips("doll_263", "sponsors_hequanshawu");
        registerSpecialTooltips("doll_264", "sponsors_zaiqiafandexiaohe_yongzhuang");
        registerSpecialTooltips("doll_265", "sponsors_xingcaodadi");
        registerSpecialTooltips("doll_266", "sponsors_fenglingyushi");
        registerSpecialTooltips("doll_267", "sponsors_cha_jiang");
        registerSpecialTooltips("doll_268", "sponsors_huanainia");
        registerSpecialTooltips("doll_269", "sponsors_pyno_lizard");
        registerSpecialTooltips("doll_270", "sponsors_artek");
        registerSpecialTooltips("doll_271", "sponsors_hoshino_shiroya");
        registerSpecialTooltips("doll_272", "sponsors_kluonuoya");
        registerSpecialTooltips("doll_273", "sponsors_mobile_mercury");
        registerSpecialTooltips("doll_274", "sponsors_siromizu");
        registerSpecialTooltips("doll_275", "sponsors_godzilla");
        registerSpecialTooltips("doll_276", "sponsors_acompaffer");
        registerSpecialTooltips("doll_277", "sponsors_ayasekou");
        registerSpecialTooltips("doll_278", "sponsors_bluesunshinecat");
        registerSpecialTooltips("doll_279", "sponsors_bnndxg");
        registerSpecialTooltips("doll_280", "sponsors_cn_shemmgdf");
        registerSpecialTooltips("doll_281", "sponsors_craneoftomorrow");
        registerSpecialTooltips("doll_282", "sponsors_creakingy");
        registerSpecialTooltips("doll_283", "sponsors_cyanleaf_ike");
        registerSpecialTooltips("doll_284", "sponsors_duskymintgear");
        registerSpecialTooltips("doll_285", "sponsors_enfluenza666");
        registerSpecialTooltips("doll_286", "sponsors_feapoi");
        registerSpecialTooltips("doll_287", "sponsors_fengbengqing_");
        registerSpecialTooltips("doll_288", "sponsors_fumoya1225");
        registerSpecialTooltips("doll_289", "sponsors_fzin");
        registerSpecialTooltips("doll_290", "sponsors_gaobai_");
        registerSpecialTooltips("doll_291", "sponsors_jiugeziqaq");
        registerSpecialTooltips("doll_292", "sponsors_kami_scarlet");
        registerSpecialTooltips("doll_293", "sponsors_koisparrow");
        registerSpecialTooltips("doll_294", "sponsors_kong_bai_ya");
        registerSpecialTooltips("doll_295", "sponsors_kumu_kia");
        registerSpecialTooltips("doll_296", "sponsors_lanxingyu520");
        registerSpecialTooltips("doll_297", "sponsors_lilyt_t");
        registerSpecialTooltips("doll_298", "sponsors_managerteaa");
        registerSpecialTooltips("doll_299", "sponsors_mar_lei");
        registerSpecialTooltips("doll_300", "sponsors_meng_kong");
        registerSpecialTooltips("doll_301", "sponsors_pandatomatoo");
        registerSpecialTooltips("doll_302", "sponsors_qfmx");
        registerSpecialTooltips("doll_303", "sponsors_qianyu7");
        registerSpecialTooltips("doll_304", "sponsors_qing_qiu_awa");
        registerSpecialTooltips("doll_305", "sponsors_qqquuuppp");
        registerSpecialTooltips("doll_306", "sponsors_sansenen_lemon");
        registerSpecialTooltips("doll_307", "sponsors_sf2403");
        registerSpecialTooltips("doll_308", "sponsors_snowstar233");
        registerSpecialTooltips("doll_309", "sponsors_snow_camellia");
        registerSpecialTooltips("doll_310", "sponsors_sunkenkeep");
        registerSpecialTooltips("doll_311", "sponsors_xiazhao01");
        registerSpecialTooltips("doll_312", "sponsors_xuehuren1");
        registerSpecialTooltips("doll_313", "sponsors_yagaoo00");
        registerSpecialTooltips("doll_314", "sponsors_yystrawberry0");
        registerSpecialTooltips("doll_315", "sponsors_z_mauthor");
        registerSpecialTooltips("doll_316", "sponsors_mingheshuimu");
        registerSpecialTooltips("doll_317", "sponsors_kehuishoulaji");
        registerSpecialTooltips("doll_318", "sponsors_liangzimaoeh");
        registerSpecialTooltips("doll_319", "sponsors_lumiya");
        registerSpecialTooltips("doll_320", "sponsors_miru_0v0");
        registerSpecialTooltips("doll_321", "sponsors_qianyue");
        registerSpecialTooltips("doll_322", "sponsors_zaocha_lanmaoczh");
        registerSpecialTooltips("doll_323", "sponsors_lfly_a");
        registerSpecialTooltips("doll_324", "sponsors_lfly_b");
        registerSpecialTooltips("doll_325", "sponsors_stormsulfur");
        registerSpecialTooltips("doll_330", "sponsors_7shu1");
        registerSpecialTooltips("doll_331", "sponsors_89623");
        registerSpecialTooltips("doll_332", "sponsors_abyssal_fish");
        registerSpecialTooltips("doll_333", "sponsors_alanwhite2006");
        registerSpecialTooltips("doll_334", "sponsors_alooooooe");
        registerSpecialTooltips("doll_335", "sponsors_anananon");
        registerSpecialTooltips("doll_336", "sponsors_aolanblue");
        registerSpecialTooltips("doll_337", "sponsors_arknights_siege");
        registerSpecialTooltips("doll_338", "sponsors_atlantary");
        registerSpecialTooltips("doll_339", "sponsors_awwwaya");
        registerSpecialTooltips("doll_340", "sponsors_bei233");
        registerSpecialTooltips("doll_341", "sponsors_bf_kanata");
        registerSpecialTooltips("doll_342", "sponsors_birch_wind_pc");
        registerSpecialTooltips("doll_343", "sponsors_buuuuuai");
        registerSpecialTooltips("doll_344", "sponsors_chenjiaqwq");
        registerSpecialTooltips("doll_345", "sponsors_chinana_kamiya");
        registerSpecialTooltips("doll_346", "sponsors_cloud369ss");
        registerSpecialTooltips("doll_347", "sponsors_cloudysoft");
        registerSpecialTooltips("doll_348", "sponsors_cmllzy");
        registerSpecialTooltips("doll_349", "sponsors_coagu1ate");
        registerSpecialTooltips("doll_350", "sponsors_co_lxhift");
        registerSpecialTooltips("doll_351", "sponsors_cygica");
        registerSpecialTooltips("doll_352", "sponsors_decib77");
        registerSpecialTooltips("doll_353", "sponsors_diemo_mustard");
        registerSpecialTooltips("doll_354", "sponsors_doctarisfishing");
        registerSpecialTooltips("doll_355", "sponsors_dong_fang_yue_yi");
        registerSpecialTooltips("doll_356", "sponsors_dream_whale");
        registerSpecialTooltips("doll_357", "sponsors_dwp0623");
        registerSpecialTooltips("doll_358", "sponsors_efanelmer");
        registerSpecialTooltips("doll_359", "sponsors_esniene");
        registerSpecialTooltips("doll_360", "sponsors_etclbe");
        registerSpecialTooltips("doll_361", "sponsors_evilestars");
        registerSpecialTooltips("doll_362", "sponsors_firudo_kagaya");
        registerSpecialTooltips("doll_363", "sponsors_floood");
        registerSpecialTooltips("doll_364", "sponsors_guonai_qwq");
        registerSpecialTooltips("doll_365", "sponsors_g_guai");
        registerSpecialTooltips("doll_366", "sponsors_hamsterbaron");
        registerSpecialTooltips("doll_367", "sponsors_haqi111");
        registerSpecialTooltips("doll_368", "sponsors_huai_zou");
        registerSpecialTooltips("doll_369", "sponsors_hubaier");
        registerSpecialTooltips("doll_370", "sponsors_h_mengm");
        registerSpecialTooltips("doll_371", "sponsors_ikun666");
        registerSpecialTooltips("doll_372", "sponsors_ivy_snu");
        registerSpecialTooltips("doll_373", "sponsors_jiaupzhuya");
        registerSpecialTooltips("doll_374", "sponsors_jjxx_s");
        registerSpecialTooltips("doll_375", "sponsors_komeijiyaku");
        registerSpecialTooltips("doll_376", "sponsors_kupurrra");
        registerSpecialTooltips("doll_377", "sponsors_kurudo_");
        registerSpecialTooltips("doll_378", "sponsors_lamerad");
        registerSpecialTooltips("doll_379", "sponsors_lankun023");
        registerSpecialTooltips("doll_380", "sponsors_lch11416");
        registerSpecialTooltips("doll_381", "sponsors_lchoip");
        registerSpecialTooltips("doll_382", "sponsors_linzijiang");
        registerSpecialTooltips("doll_383", "sponsors_lixingyu");
        registerSpecialTooltips("doll_384", "sponsors_llama_potato");
        registerSpecialTooltips("doll_385", "sponsors_lon314");
        registerSpecialTooltips("doll_386", "sponsors_lovely_xier");
        registerSpecialTooltips("doll_387", "sponsors_lshnoodle");
        registerSpecialTooltips("doll_388", "sponsors_macbookair0219");
        registerSpecialTooltips("doll_389", "sponsors_marrytat");
        registerSpecialTooltips("doll_390", "sponsors_max__payne");
        registerSpecialTooltips("doll_391", "sponsors_mengitou");
        registerSpecialTooltips("doll_392", "sponsors_mu_xiaomu");
        registerSpecialTooltips("doll_393", "sponsors_nainmoon");
        registerSpecialTooltips("doll_394", "sponsors_normal_sd");
        registerSpecialTooltips("doll_395", "sponsors_ogeetarclove");
        registerSpecialTooltips("doll_396", "sponsors_oorionzev");
        registerSpecialTooltips("doll_397", "sponsors_ovofufu");
        registerSpecialTooltips("doll_398", "sponsors_probie_123");
        registerSpecialTooltips("doll_399", "sponsors_qingliu_pro");
        registerSpecialTooltips("doll_400", "sponsors_qitiang");
        registerSpecialTooltips("doll_401", "sponsors_qt_tong");
        registerSpecialTooltips("doll_402", "sponsors_qwq_ender");
        registerSpecialTooltips("doll_403", "sponsors_qxiaoshp81");
        registerSpecialTooltips("doll_404", "sponsors_relicnila");
        registerSpecialTooltips("doll_405", "sponsors_rimuj");
        registerSpecialTooltips("doll_406", "sponsors_rjmc");
        registerSpecialTooltips("doll_407", "sponsors_s1mon_l");
        registerSpecialTooltips("doll_408", "sponsors_savy116");
        registerSpecialTooltips("doll_409", "sponsors_sharq_r");
        registerSpecialTooltips("doll_410", "sponsors_shianye");
        registerSpecialTooltips("doll_411", "sponsors_shirasawa_tobi");
        registerSpecialTooltips("doll_412", "sponsors_shuzimo");
        registerSpecialTooltips("doll_413", "sponsors_sierbar");
        registerSpecialTooltips("doll_414", "sponsors_singleorange");
        registerSpecialTooltips("doll_415", "sponsors_sisil89");
        registerSpecialTooltips("doll_416", "sponsors_skdmywife");
        registerSpecialTooltips("doll_417", "sponsors_slandre");
        registerSpecialTooltips("doll_418", "sponsors_sugar");
        registerSpecialTooltips("doll_419", "sponsors_teacher_dai");
        registerSpecialTooltips("doll_420", "sponsors_venetoquincy");
        registerSpecialTooltips("doll_421", "sponsors_void060729");
        registerSpecialTooltips("doll_422", "sponsors_watermonstersub");
        registerSpecialTooltips("doll_423", "sponsors_wensleep");
        registerSpecialTooltips("doll_424", "sponsors_windfallingdust");
        registerSpecialTooltips("doll_425", "sponsors_winthre");
        registerSpecialTooltips("doll_426", "sponsors_wulitree");
        registerSpecialTooltips("doll_427", "sponsors_wuxijiang");
        registerSpecialTooltips("doll_428", "sponsors_w_recluse");
        registerSpecialTooltips("doll_429", "sponsors_xiao_chenk");
        registerSpecialTooltips("doll_430", "sponsors_yi");
        registerSpecialTooltips("doll_431", "sponsors_youyo_tea");
        registerSpecialTooltips("doll_432", "sponsors_yuejiu0wolf");
        registerSpecialTooltips("doll_433", "sponsors_yuemomu");
        registerSpecialTooltips("doll_434", "sponsors_yuguo_dada");
        registerSpecialTooltips("doll_435", "sponsors_yukiha0309");
        registerSpecialTooltips("doll_436", "sponsors_zecheng");
        registerSpecialTooltips("doll_437", "sponsors_zzdz1");
        registerSpecialTooltips("doll_438", "sponsors_yinan_youyizhangfaguangwenli");
        registerSpecialTooltips("doll_439", "sponsors_qi");
        registerSpecialTooltips("doll_440", "sponsors_gubao");
        registerSpecialTooltips("doll_441", "sponsors_lapudantuiren_hukefu");
        registerSpecialTooltips("doll_442", "sponsors_muan");
        registerSpecialTooltips("doll_443", "sponsors_yumu");
        registerSpecialTooltips("doll_444", "sponsors_youyingshadow");
        registerSpecialTooltips("doll_445", "sponsors_xuanlin");
        registerSpecialTooltips("doll_446", "sponsors_qiuku");
        registerSpecialTooltips("doll_447", "sponsors_yueaximu");
        registerSpecialTooltips("doll_448", "sponsors_zhuyan");
        registerSpecialTooltips("doll_449", "sponsors_yumo");
        registerSpecialTooltips("doll_450", "sponsors_feiqichanchan");
        registerSpecialTooltips("doll_451", "sponsors_yumian");
        registerSpecialTooltips("doll_452", "sponsors_lei_yinqwq");
        registerSpecialTooltips("doll_453", "sponsors_coppercuo");
        registerSpecialTooltips("doll_454", "sponsors_sodatnt");
        registerSpecialTooltips("doll_455", "sponsors_nanayu");
        registerSpecialTooltips("doll_456", "sponsors_wenquxin");
        registerSpecialTooltips("doll_457", "sponsors_wuyu");
    }

    @SubscribeEvent
    public static void registerBlocks(RegisterEvent event) {
        registerAllVanillaTooltips();
        registerAllSpecialTooltips();
        // 批量注册玩偶
        if (event.getRegistryKey().equals(ForgeRegistries.BLOCKS.getRegistryKey())) {
            IntStream.range(0, MAX_DOLL_COUNT).forEach(i -> {
                ResourceLocation name = new ResourceLocation(KaleidoscopeDoll.MOD_ID, "doll_" + i);
                DollBlock block = new DollBlock();
                DOLL_BLOCKS.put(name, block);
                event.register(ForgeRegistries.BLOCKS.getRegistryKey(), name, () -> block);
            });
        }
        if (event.getRegistryKey().equals(ForgeRegistries.ITEMS.getRegistryKey())) {
            IntStream.range(0, MAX_DOLL_COUNT).forEach(i -> {
                ResourceLocation name = new ResourceLocation(KaleidoscopeDoll.MOD_ID, "doll_" + i);
                DollBlock block = DOLL_BLOCKS.get(name);
                String vanillaDesc = VANILLA_TOOLTIPS.getOrDefault(name, "vanilla");
                String specialDesc = SPECIAL_TOOLTIPS.getOrDefault(name, vanillaDesc);
                Item item = new DollItem(block, specialDesc);
                DOLL_ITEMS.add(item);
                event.register(ForgeRegistries.ITEMS.getRegistryKey(), name, () -> item);
            });
        }
    }

    private static void registerVanillaTooltips(String name, String tooltip) {
        ResourceLocation id = new ResourceLocation(KaleidoscopeDoll.MOD_ID, name);
        VANILLA_TOOLTIPS.put(id, tooltip);
    }

    private static void registerSpecialTooltips(String name, String tooltip) {
        ResourceLocation id = new ResourceLocation(KaleidoscopeDoll.MOD_ID, name);
        SPECIAL_TOOLTIPS.put(id, tooltip);
    }
}
